#yaml file for workflow configuration on push to main branch
name: Python Application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.19
    # operations defined in the Makefile
    - name: Install dependencies
      run: |
        make install
    - name: Check if test directory exists
      id: check_tests
      run: |
        if [ -d "./test" ]; then
          echo "tests_exist=true" >> $GITHUB_OUTPUT
        else
          echo "tests_exist=false" >> $GITHUB_OUTPUT
        fi
    - name: Run tests
      if: steps.check_tests.outputs.tests_exist == 'true'
      run: |
      make test
    - name: Run formatting
      run: |
        make format
    - name: Lint code
      run: |
        make lint
