#yaml file for workflow configuration on push to main branch
nname: Python Application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.11
      # operations defined in the Makefile
      - name: Install dependencies
        run: |make install
      - name: Run tests
        run: |make test
      - name: Run formatting
        run: |make format
      - name: Lint code
        run: |make lint
